/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tasks${'/(home)'}` | `/tasks`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tickets/CreateTicket` | `/tickets/CreateTicket`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tickets/dashboard` | `/tickets/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tickets` | `/tickets`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tasks${'/(home)'}/[id]` | `/tasks/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(tabs)'}/tickets/[id]` | `/tickets/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/tasks${'/(home)'}` | `/tasks`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/tickets/CreateTicket` | `/tickets/CreateTicket`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/tickets/dashboard` | `/tickets/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/tickets` | `/tickets`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/tasks${'/(home)'}/[id]` | `/tasks/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `${'/(tabs)'}/tickets/[id]` | `/tickets/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/tasks${'/(home)'}${`?${string}` | `#${string}` | ''}` | `/tasks${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/tickets/CreateTicket${`?${string}` | `#${string}` | ''}` | `/tickets/CreateTicket${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/tickets/dashboard${`?${string}` | `#${string}` | ''}` | `/tickets/dashboard${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/tickets${`?${string}` | `#${string}` | ''}` | `/tickets${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tasks${'/(home)'}` | `/tasks`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tickets/CreateTicket` | `/tickets/CreateTicket`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tickets/dashboard` | `/tickets/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tickets` | `/tickets`; params?: Router.UnknownInputParams; } | `${'/(tabs)'}/tasks${'/(home)'}/${Router.SingleRoutePart<T>}` | `/tasks/${Router.SingleRoutePart<T>}` | `${'/(tabs)'}/tickets/${Router.SingleRoutePart<T>}` | `/tickets/${Router.SingleRoutePart<T>}` | { pathname: `${'/(tabs)'}/tasks${'/(home)'}/[id]` | `/tasks/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(tabs)'}/tickets/[id]` | `/tickets/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
